[package]
name = "ai-arena-client-gui"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "ai-arena-client-gui"
edition = "2018"
build = "src/build.rs"

[dependencies]
aiarena-client-gui-backend = { path = "../backend" }
serde_json = "^1.0"
serde = { version = "^1.0", features = [ "derive" ] }
tauri = { version = "0.11.1", features = [ "all-api" ] }
env_logger = "^0.8"

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "ai-arena-client-gui"
path = "src/main.rs"

[build-dependencies]
aiarena-client-gui-backend = { path = "../backend" }
