version: 2
updates:
- package-ecosystem: cargo
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/src-tauri"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
